name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if you're using a different branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the provided GitHub token
          publish_dir: .  # Specify the directory to publish
