name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch (main or master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Use the latest version
        with:
          node-version: '20'  # Use Node.js 20 to avoid deprecation issues

      - name: Install dependencies
        run: npm install  # Use this if you have dependencies to install

      - name: Build
        run: npm run build  # Run the build command if necessary

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Change this if your index.html is in a subfolder
