name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Latest version
        with:
          node-version: '20'  # Use Node.js 20

      - name: Install dependencies
        run: |
          npm install  # Run this if you have a package.json

      - name: Build project
        run: |
          npm run build  # Run this if you have a build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Serve from the root directory
